### ISSUE TITLE
X3DOM ComposedShader not working on my BinaryGeometry data

### ISSUE THREAD

**Issue by styxsys0927** [x3dom/x3dom#1017]
This is my first post, so please let me know if I miss anything...

I'm trying to use ComposedShader in X3DOM to change the sizes of points in a point cloud. My shader works fine on both PointSet or X3DOM example BinaryGeometry, but it doesn't work on my own BinaryGeometry data (the point cloud doesn't show up). My point cloud can be rendered without the shader or with "material" instead, though.

There are not any messages showed in my console and I really have no clue what can be wrong except for a large number of points in my point cloud (1146222... not so large actually...).

Here are the core parts of my code:
`<shape DEF='SP_0'>

            <Appearance>
              <ComposedShader>
                
                <ShaderPart type='VERTEX' style="display:none;">
                  attribute vec3 position;
                  attribute vec3 color;

                  uniform mat4 modelViewProjectionMatrix;

                  varying vec3 col;

                  void main()
                  {
                  gl_Position = modelViewProjectionMatrix * vec4(position, 1.0);
                  gl_PointSize = max( 200.0 / gl_Position.w, 1.0);
                  col = color;
                  }
                </ShaderPart>
                <ShaderPart type='FRAGMENT' style="display:none;">
                  #ifdef GL_FRAGMENT_PRECISION_HIGH
                  precision highp float;
                  #else
                  precision mediump float;
                  #endif

                  uniform vec3 light0_Direction;
                  uniform sampler2D u_texture;

                  varying vec3 col;

                  void main()
                  {
                  gl_FragColor = vec4(col, 1.0);
                  }
                </ShaderPart>
              </ComposedShader>
            </Appearance>
            <binaryGeometry id="bg0" DEF='BG_0'
                            vertexCount='1146222'
                            primType='"POINTS"'
                            position='247.080001831 126.869995117 -19.8899993896'
                            size='563.619995117 505.299987793 84.7600021362'
                            coord='aopt50BG_0_coordBinary.bin+8'
                            color='aopt50BG_0_colorBinary.bin+4'
                            coordType='Int16' colorType='Uint8'>

            </binaryGeometry>
          </shape>`

**Comment by andreasplesch** [comment]
https://jsitor.com/xhUGVGZFK

is the shader with a regular PointSet and it works fine, as you say.

Can you provide your binary geometry ? A minimal example ?

**Comment by styxsys0927** [comment]
Thank you for reply! Here are my data.

[aopt50BG.zip](https://github.com/x3dom/x3dom/files/3812382/aopt50BG.zip)

**Comment by andreasplesch** [comment]
https://raw.githack.com/andreasplesch/Library/39ce6322218dd534b78e01a05759721b956b1661/Examples/bingeo/bingeoShader.html
has a fixed custom shader.

The problem was that aopt generates scaled and shifted coordinates to utilize the full precision of storage format. This is why there are the position and size fields for binaryGeometry.
With a regular Material, uniforms for those fields are made available to the default shader but with a ComposedShader they are not. So I just provided those as constants manually in the shader. Also, colors are scaled and have to be unscaled.

https://chrome.google.com/webstore/detail/spectorjs/denbgaamihkadbghdceggmchnflmhpmk?hl=en was very helpful with debugging the shader. It worked well.

Are these LIDAR scanned points ?

BufferGeometry may be another option for binary geometry loading. It is used currently for gltf loading but I think could be used independent of gltf.

**Comment by andreasplesch** [comment]
The number of points does not seem to be problem, even on mobile.

**Comment by andreasplesch** [comment]
It turns out that the bg related uniforms (bgSize, bgCenter ..) are actually available in a custom shader:

https://raw.githack.com/andreasplesch/Library/35a7fdb2ecc5979532c084842b0c22c39d458ec2/Examples/bingeo/bingeoShader.html

(for non float, eg. int coord/color buffers).

So this should work more generally for other content.

**Comment by andreasplesch** [comment]
The revised shader
```js
						<ShaderPart type='VERTEX' style="display:none;">
attribute vec4 position;
attribute vec3 color;

uniform mat4 modelViewProjectionMatrix;
uniform vec3 bgSize;
uniform vec3 bgCenter;
uniform float bgPrecisionMax;
uniform float bgPrecisionColMax;

varying vec3 col;

void main()
{
	vec3 vertPosition = position.xyz;
	vertPosition = bgCenter + bgSize * vertPosition / bgPrecisionMax;

	gl_Position = modelViewProjectionMatrix * vec4(vertPosition, 1.0);
	gl_PointSize = max( 200.0 / gl_Position.w, 1.0);
	col = color / bgPrecisionColMax;
}
						</ShaderPart>
```

**Comment by styxsys0927** [comment]
Thank you so much! It works perfectly for me!

**Comment by andreasplesch** [comment]
You are welcome. Feel free to post to the x3dom-user list if you want to share a cool point cloud scene.
