### ISSUE TITLE
Feature Request: Partial x3dom bundle 

### ISSUE THREAD

**Issue by mithi** [x3dom/x3dom#1104]
When downloaded, x3dom is about 1.2 MB. It's extremely large. 

Would it be easy to provide an alternative script that has only the bare minimum features... ie 
just for rendering a scene with a line, box, sphere and cone, that can be rotated and translated?

If I were only be rendering something like this (below) would it be easy to remove all the unused code? 

```html
<x3d width='500px' height='400px'> 
  <scene> 
    <shape>
      <appearance> 
        <material diffuseColor='1 0 0'></material> 
      </appearance> 
      <box size='0.1,4,5' solid='false'></box> 
    </shape> 
   
    <transform translation='-5 0 0'> 
      <shape> 
        <appearance> 
	  <material diffuseColor='0 1 0'></material> 
	</appearance> 
	<cone side="true" subdivision='32' lit='true' top='false' topRadius='3' solid='false'></cone> 
      </shape> 
  </transform>

  </scene> 
</x3d>

**Comment by andreasplesch** [comment]
I am sorry to report there are no plans to provide a more minimal prepackaged script unless somebody wants to contribute. Just note that the actual download size is about 240kb due to automatic compression if you check in dev tools. 

If you are interested, it should be possible to tweak the build configuration and build locally. You probably could get rid of many concrete nodes, in https://github.com/x3dom/x3dom/blob/master/build/core/packages.json. To do that it may make sense to become familiar with x3d architecture: https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/X3D.html

**Comment by mithi** [comment]
> I am sorry to report there are no plans to provide a more minimal prepackaged script unless somebody wants to contribute. Just note that the actual download size is about 240kb due to automatic compression if you check in dev tools.
> 

Thanks for the reply, I'll try understand this library enough and hopefully be able to build a more minimal script. 
I hope I can use x3dom to make 3d line + scatter plot  (Replacing Plotly) in this project:

https://github.com/mithi/hexapod

![](https://camo.githubusercontent.com/3d6e362ffe4a75d06997ec5f9fabada6336aeb92/68747470733a2f2f6d697468692e6769746875622e696f2f726f626f746963732d626c6f672f73686f772d6f66662e676966)

Thanks again!

**Comment by andreasplesch** [comment]
Cool project. x3dom will be quite different from Plotly, so this may involve some effort.

Thick lines do not work very well due to webgl limitations. Cylinders or long boxes and spheres could work well. Also note that x3d does not use Euler angles but axis-angle notation. You can also use matrices or quaternions.

**Comment by andreasplesch** [comment]
x3dom comes with a quite complete math library (fields.js). You may be able to use it more generally, eg. outside of x3dom.
