### ISSUE TITLE
porting webVR to webXR

### ISSUE THREAD

**Issue by leoull** [x3dom/x3dom#1112]
I have been trying to implement WebXR to replace the now deprecated WebVR. the code I am trying to upgrade is https://x3dom.org/download/1.8.1/x3dom.js, which has the depreciated WebVR API in it and I am trying to replace the WebVR code to WebXR code using a GitHub guide (https://github.com/immersive-web/webxr/blob/master/webvr-migration.md). is this even the right approach? has anyone upgraded the x3dom.js file to use WebXR by now?

**Comment by andreasplesch** [comment]
Hi there, yes, that would be right approach. and any progress would be very welcome. It may be more comfortable to fork x3dom and work on a feature branch of the current master rather than on 1.8.1. This would also allow for submitting PRs. Porting to WebXR should be very doable. More generally speaking navigation and controller use in VR will need attention, after the porting.

**Comment by leoull** [comment]
@andreasplesch Thank you!
