### ISSUE TITLE
Picking for sized points not working

### ISSUE THREAD

**Issue by styxsys0927** [x3dom/x3dom#1150]
I'm trying to produce a scene with millions of sized points (pointset+pointproperties or particleset) with each point pickable like the x3dom example [https://doc.x3dom.org/tutorials/animationInteraction/pickingBuffer/example.html](url). However, I found that even if the points seem like a large circle, I could only pick a point when I clicked exactly at the center of the circle. Besides, it seems that there are no collision effects among points, i.e., I can pick a point even though it seems "hidden" behind another point.

Here is a simple example modified from the x3dom picking buffer example [https://github.com/styxsys0927/x3dom-point-cloud-demo/blob/main/sprite_picking_simple.html](url). Thanks in advance!

**Comment by andreasplesch** [comment]
for convenience: https://raw.githack.com/styxsys0927/x3dom-point-cloud-demo/main/sprite_picking_simple.html

https://raw.githack.com/x3dom/x3dom/master/test/regression-suite/test/cases/points/ArchimedesPointProperties.html
shows the same behaviour, eg. requires clicking on the center, the exact point.

I think it has to do with how point properties are not considered in the picking shader:
https://github.com/x3dom/x3dom/blob/master/src/shader/ShaderDynamicPicking.js

It may be possible to transfer the relevant shader code from the regular shader:
https://github.com/x3dom/x3dom/blob/master/src/shader/ShaderDynamic.js

Please feel free to give it a try.

**Comment by andreasplesch** [comment]
It seemed like a tractable issue to make some progress on. Here is a preview build:

https://6037205c8820e100079d41fd--x3dom.netlify.app/x3dom-full.debug.js

and here the repo example:
https://6037205c8820e100079d41fd--x3dom.netlify.app/examples/cases/points/archimedespointproperties

Please give the build a try. Thanks.

**Comment by styxsys0927** [comment]
Hi @andreasplesch,

It looks great to me! Thanks!

May I know if you have modified any code aside from the dynamic picking shader generation?

Thanks again!

**Comment by andreasplesch** [comment]
Super. Feel free to look at the commits on

https://github.com/andreasplesch/x3dom/commits/pointPicking

Besides work on the shader, it was also necessary to pass uniforms for point size etc. to the shader from gfx_webgl.js . Adding a property to the "sp" shader object automagically passes its value to the shader uniform. The file needs to be refactored and split up . Ultimately, it would be best to rewrite with shader chunks leaning heavily on three but this is unrealistic.

The picking shader generally does not consider textures, so textured sprites are always squares for picking (but untextured points are circles). In principle, it would be possible to check for transparent alpha after texturing in the picking shader as well but probably only optionally and for a very significant use case due to performance concerns (a lot of rendering each frame).

The older x3dom ParticleSet has the same issue, and I included preparations for it in the updated shader. There is perhaps not too much missing to make it work but it would be a departure from the existing behavior.

I will let the pointPicking branch sit there for a bit in case some idea or issue comes up, and then probably submit a PR to the main repo.

**Comment by styxsys0927** [comment]
Thank you! Really appreciate the explanation!
