### ISSUE TITLE
Documentation for using npm installed x3dom

### ISSUE THREAD

**Issue by mikeaustin** [x3dom/x3dom#1162]
It seems that x3dom does have an npm package available, but it's not clear how to use it – on the home page or in the documentation. The only export I see using "import * as x3dom" is "Zlib". Looking at node_modules/x3dom/x3dom.js there are no "module.exports" that I can see. It doesn't seem like window globals are installed either, such as "shape" or "box".

So my request is to better describe how to use x3dom using npm (and webpack). Many, many people use webpack and other packaging tools for web development. As it is right now, I and likely others are clueless on how to use x3dom.

**Comment by andreasplesch** [comment]
Here is a possible webpack setup based on the webpack documentation on globals:

https://webpack.js.org/guides/shimming/#global-exports

https://stackblitz.com/edit/github-p9hpwk?file=src/index.js

exports-loader can make the x3dom global available. Probably there are better ways to do that since I am unfamiliar with webpack.

For simple projects which do not need access to the x3dom global , it looks like it is possible to just require x3dom:

https://stackblitz.com/edit/github-p9hpwk-azbwdg?file=src/index.js

**Comment by andreasplesch** [comment]
Please reopen when needed.
