### ISSUE TITLE
<navigationinfo type="game"> causes crash

### ISSUE THREAD

**Issue by microaaron** [x3dom/x3dom#1187]
@andreasplesch 
Here is the example:
[https://jsitor.com/lOobY2Ggp](https://jsitor.com/lOobY2Ggp)

Error information:

x3dom-full.debug.js:17225 Uncaught TypeError: Cannot read properties of null (reading '_scene')
    at Context.x3dom.gfx_webgl.Context.shutdown (x3dom-full.debug.js:17225)
    at x3dom.X3DDocument.shutdown (x3dom-full.debug.js:21914)
    at onunload (x3dom-full.debug.js:20135)
    at 0.0c8f88f4.chunk.js:1

**Comment by npolys** [comment]
that page is 404

**Comment by andreasplesch** [comment]
Please feel free to reopen when appropriate.

**Comment by microaaron** [comment]
> that page is 404

https://jsitor.com/WU_VlipWvy

···
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta http-equiv="X-UA-Compatible" content="chrome=1,IE=edge" />
	<script type="text/javascript" src="https://x3dom.org/release/x3dom-full.debug.js"></script>
	<link rel='stylesheet' type='text/css' href='https://www.x3dom.org/release/x3dom.css'>
	</link>
</head>

<body>
	<X3D id="x3d" showLog="false" width="600px" height="500px">
		<Scene>
	    <navigationinfo type="game">
		</Scene>
	</X3D>
</body>

</html>
···

**Comment by andreasplesch** [comment]
Ok, thanks. I could reproduce this.
https://jsitor.com/XTwUX_a6mI
has a patched NavigationInfo node which guards against the error. The problem is that the viewarea is not available yet when initializing game mode.  The workaround is to use examine mode first and the switch to game mode, with the keyboard or the runtime.
A fix may be to always call initmouseState() after instantiating a new viewarea.

**Comment by microaaron** [comment]
Thanks.
