### ISSUE TITLE
Typescript definition files

### ISSUE THREAD

**Issue by doczoidberg** [x3dom/x3dom#221]
Are typescript (http://www.typescriptlang.org/) definition files anywhere available for x3dom? Or is there a plan to write some?

**Comment by JirkaDellOro** [comment]
Still no plans? As Typescript is becoming more popular it would probably help x3dom.

**Comment by andreasplesch** [comment]
AFAIK this is still the case since it takes resources and the cost apparently outweighed the need, sofar. If TS definitions can be incrementally improved and accumulated, perhaps there is an opportunity for a contributing project, driven by consumers.

**Comment by JirkaDellOro** [comment]
Maybe it's going to be interesting for me to contribute. But... is x3dom still very alive? There is little acitivity here on github...

**Comment by andreasplesch** [comment]
If you have a specific target or app in mind, why not contribute back ? X3D is well suited since it has a strong, abstract, language independent specification with strongly typed fields and nodes. As such it could be also a fun project and will probably discover many quirks and bugs/oversights in the code base.
x3dom is best seen as part of a larger X3D ecosystem which is still pretty significant, eg. they are serious web apps using x3dom.
But I think it would pretty important to have a specific target, find a way to make it a good experience and to be prepared that progress may be slow. The only way to find out if there is broader interest would be to get started somehow.

**Comment by coderextreme** [comment]
[uomzod.txt](https://github.com/user-attachments/files/25572327/uomzod.txt)  Experimental Zod schema for X3D (AI generated).
