### ISSUE TITLE
Uncaught TypeError: Cannot read property '_vf' of null    (w/stacktrace)

### ISSUE THREAD

**Issue by simonthum** [x3dom/x3dom#361]
I'm getting this whenever I add an inline node from javascript. My suspicion is that the onreadystatechange does a bit too much, but I'm not well prepared to assess that in detail.

Uncaught TypeError: Cannot read property '_vf' of null x3dom.js:2561
x3dom.registerNodeType.defineClass.nodeChanged x3dom.js:2561
x3dom.NodeNameSpace.setupTree x3dom.js:2257
(anonymous function) x3dom.js:2257
Array.forEach x3dom.js:2
x3dom.NodeNameSpace.setupTree x3dom.js:2257
(anonymous function) x3dom.js:2257
Array.forEach x3dom.js:2
x3dom.NodeNameSpace.setupTree x3dom.js:2257
(anonymous function) x3dom.js:2257
Array.forEach x3dom.js:2
x3dom.NodeNameSpace.setupTree x3dom.js:2257
(anonymous function) x3dom.js:2257
Array.forEach x3dom.js:2
x3dom.NodeNameSpace.setupTree x3dom.js:2257
(anonymous function) x3dom.js:2257
Array.forEach x3dom.js:2
x3dom.NodeNameSpace.setupTree x3dom.js:2257
(anonymous function) x3dom.js:2257
Array.forEach x3dom.js:2
x3dom.NodeNameSpace.setupTree x3dom.js:2257
xhr.onreadystatechange

**Comment by coderextreme** [comment]
If you add the Coordinate element to the IndexedTriangleSet element before you add the IndexedTriangleSet to the DOM, it's likely you will not suffer from this issue.  Also IndexedFaceSet is similar.  In general, add children and descendents to the to their own DOM before you add parent's DOM, if adding the nodes with JavaScript.  I imagine it could be painful to change X3DOM to incorporate adding Coordinate after the Indexed Set, but I don't really know.

**Comment by simonthum** [comment]
Hi, the issue is long gone and I wasn't even scripting - my actual itch is the message being less than helpful for disagnosis. I guess it's still like that since you found this odd place...

**Comment by coderextreme** [comment]
Yep, the issue is still open.  I also get an error with getPoints() at the same time, which may help with diagnosis.

**Comment by andreasplesch** [comment]
I was  tring to find some guidance in the spec. on what behaviour is expected if the coord node is not provided. The default value for the coord node is NULL
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/rendering.html#IndexedTriangleSet
NULL here probably means that the node exists but is unitialized ? But NULL is hard to use:
http://stackoverflow.com/questions/2707322/what-is-null-in-java
The language binding spec. has more
http://www.web3d.org/documents/specifications/19777-1/V3.3/Part1/concepts.html#NULLNodes
which refers back to the default behaviour of the parent node.
However, the parent node does not seem to define a default behaviour or geometry if coord is NULL. So the spec. does not seem to provide guidance and seems to defer to individual browser decisions.
In that sense the x3dom behaviour of bailing is ok although it may not really be user friendly.
Would it perhaps make sense to add a
```
if(coordNode == null) {
  x3dom.debug.logWarning('No coord node yet -> no geometry to render'); return;}
```
or similar before the access to the coordNode in order to catch the error  ?
The fieldChanged function should already deal then with an updated coord node which then has coordinates. Although it may need to check if the coord field is empty.
These types of errors may become more common since the browser dom and javascript encourages programmatic construction of an x3d scene (through libraries such as jquery  or d3).

**Comment by coderextreme** [comment]
As far as I can tell, it has nothing to do with d3 or jquery and has
everything to do with appending the indexed set before appending the
coordinate using DOM functions which affect both d3 and jquery.  Appending
the coordinate to the indexed set and then appending the indexed set to the
rest of the DOM should work fine.  I don't view this as onerous in my code,
but other may think so.

**Comment by simonthum** [comment]
@andreasplesch  Thanks for providing insights to the spec. Technically, in javascript `null` is positively "not there", i.e. there is something that might exist but it  doesn't. The `null` you assume would be `undefined` in js.

In any case it would make a lot of sense to be more user-friendly and handle nodes that get set to null after being object before throughout the update handlers. Setting nodes to undefined does not make any sense, it's the logical equivalent of saying the `SF_Node field` is not there. I guess the spec does not cover runtime removal of fields, although js can do that.

**Comment by andreasplesch** [comment]
So I am not sure if javascript `null` corresponds to the NULL intended in the spec. It may not since the spec. may consider the fields of an object to be always existing.
I believe runtime removal of nodes would be covered by the SAI part of the spec. if it is.

**Comment by simonthum** [comment]
I think the correspondence is there, i.e. that ``js null == X3D NULL``. The SF_Node field is there, just its value happens to be `null`. That is, there is a field without a node.

I was trying to say that `undefined` is a state not treated by X3D, and that field (non-)existence could be a logical equivalent but that's out of scope for this bug and even for the purposes of X3D as otherwise the ecmascript binding wouldn't be silent about it.

**Comment by coderextreme** [comment]
For me, the node isn’t there yet, since I am creating DOM from JSON.  The solution was to build the child node first, then add it to the parent, then add the parent.  Before that, the code would die in the appendChild.

John
