### ISSUE TITLE
x3dom.css should only change the style of X3DOM elements

### ISSUE THREAD

**Issue by mabuchner** [x3dom/x3dom#488]
x3dom.css should only change the style of X3DOM elements.

I really don't like that x3dom.css changes the style of the "body" element. Changing the style of every "object" element probably also is not a good thing.

**Comment by hapztron** [comment]
I think so.

x3dom.css should not changes the style of the element, like html, body, or even x3dom element itself. Should use classname instead of element. And maybe we should add some rule for using x3dom.css, like specific id or classname.

I could help for this.

--
Best Regards / Mit freundlichen Grüßen

Hassadee Pimsuwan
Front-End Developer & Web3D Developer

Email: hapztron@gmail.com <mailto:hapztron@gmail.com>
Blog: http://hassadee.com <http://hassadee.com/>
Mobile: +66(0)8-7778-7806

**Comment by mlimper** [comment]
Thanks for your interest in improving this!
Please feel free to submit a pull request if you have something to share.

Ideally, we would make sure that all the current examples and applications still look the same, where possible. The font of the body, for example, is not important though, I totally agree that it does definitely not belong into X3DOMs CSS file.

**Comment by jamesleesaunders** [comment]
It looks like this was resolved by commit a5bf1c3b18998da7ccf7b8d38da30de510e8dbbb ?
Think this issue can be closed?

**Comment by andreasplesch** [comment]
I suspect that the object element styling was linked to the flash based renderer. If so, it should be removed in the css as well. Let's close this, and open a new issue for the object styling.

**Comment by jamesleesaunders** [comment]
That’s 3 issues closed this week :-)
