### ISSUE TITLE
onclick, on geometry, fails in WALK mode

### ISSUE THREAD

**Issue by sguynup** [x3dom/x3dom#492]
To see - go to and try the center cube:
http://doc.x3dom.org/tutorials/basics/htmlCSS/HTMLEventsCSS.html

then press "w" for walk...and you get no action from onclick
(examine and fly are fine)

happens in Windows 8.1 - Firefox / IE / Chrome  and on a Mac

**Comment by sressler** [comment]
It does respond differently when in walk...but if I walk up to the center
cube so that it almost fills the canvas it does respond.  Walk away so that
cube is small and it stops responding (on Mac)

On Sun, May 3, 2015 at 8:16 PM, sguynup <notifications@github.com> wrote:

> To see - go to and try the center cube:
> http://doc.x3dom.org/tutorials/basics/htmlCSS/HTMLEventsCSS.html
>
> then press "w" for walk...and you get no action from onclick
> (examine and fly are fine)
>
> happens in Windows 8.1 - Firefox / IE / Chrome and on a Mac
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x3dom/x3dom/issues/492>.
>



-- 

Sandy Ressler

http://www.sandyressler.com @sressler

http://www.bitcoininplainenglish.com  @btcplainenglish

sressler at acm.org

**Comment by tsturm** [comment]
Should be fixed with my last commit.

Can you test it again with latest dev-version?

**Comment by sguynup** [comment]
It works (absolutely sweet) - thank you.
