### ISSUE TITLE
Moving inside a volume makes volume disappear

### ISSUE THREAD

**Issue by mlimper** [x3dom/x3dom#537]
As reported by a user of the volume rendering component:

When attempting to move within a volume, it suddenly disappears. This 
appears to be related to the proximity of the user/camera. When I move 
away from the volume, it reappears.  I call this a bug because there is 
no way for me to be within the volume and look around to see the 
relationship of any structures within that volume.

**Comment by mlimper** [comment]
@aarbelaiz do you think you could have a look?

**Comment by aarbelaiz** [comment]
The current volume rendering algorithm does not support to locate the camera inside the volume. The volume is rendered in the outside surface of a cube, when the camera goes inside the volume it disappears because both the front-faces and the back-faces of the cube are needed to render the volume.
This is a feature not a bug, an alternative rendering algorithm will be needed to achieve such result. A way to see into the volume is modifying the opacity with a transfer function.

**Comment by onehalfmv2** [comment]
Hi!!  I am the user who reported the above behavior.  I think that an alternative rendering algorithm would be a great thing!  Part of the power of volumes, especially with medical imaging, is the ability to move the camera within them to understand the complex spatial relationships between the different anatomical entities.  The experience would be especially powerful with segmentation of the volume plus a HMD.

**Comment by mlimper** [comment]
@aarbelaiz Thanks for providing some insight on the rendering algorithm!
Could we briefly sum up how the current version works, and how an alternative approach would look like? Are you doing some form of raycasting and using the planes of the cube as image planes?

**Comment by npolys** [comment]
and relatedly, would clipping planes work with both 'methods'?

br,
_n

On Thu, Aug 20, 2015 at 6:11 AM, Max Limper <notifications@github.com>
wrote:

> @aarbelaiz <https://github.com/aarbelaiz> Thanks for providing some
> insight on the rendering algorithm!
> Could we briefly sum up how the current version works, and how an
> alternative approach would look like? Are you doing some form of raycasting
> and using the planes of the cube as image planes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x3dom/x3dom/issues/537#issuecomment-132964635>.
>



-- 
Nicholas F. Polys, Ph.D.

Director of Visual Computing
Virginia Tech Research Computing

Affiliate Professor
Virginia Tech Department of Computer Science

**Comment by aarbelaiz** [comment]
Well, I think that obtaining a volume rendering output when the camera is inside the volume could be compatible with the current approach, but there are multiple facts to consider:

- Any improvement will imply changes on the current GLSL shaders and there will be conditional branching (a bunch of annoying if-else's in the GLSL code, which kills the performance). Thus, a performance loss will be expected, specially when looking inside the volume is not the main use case.

- As the GLSL rayscasting shaders is generated dynamically when the X3D scene is loaded, this feature could be conditionally enabled with a new attribute on the VolumeData node, like `solid=false` or `enableInsideLook=true`, so a modification/addition to the X3D node should be discussed. Also, compatibility with the current styles and in which cases makes sense to enable it should be studied. 


@mlimper The volume rendering technique is achieved by casting a ray from the camera viewpoint towards a box and transforming the ray position into 3D texture coordinates (given as a 2D Atlas). 

The initial approach is described in:
[Volume Ray Casting in WebGL](http://cdn.intechopen.com/pdfs-wm/34474.pdf)

The current approach is a refined version which uses a single-pass instead of a two-passes strategy. The 3D coordinates of the cube are transformed into 3D texture coordinates and the camera location is used to calculate the ray direction.


@npolys About the clipping planes for volume rendering, I guess they should be implemented as shader clipping planes which will require further modification of the shaders. The clipping plane information should be made somehow available in the shader. 

In theory, adding clipping planes should be possible in the current implementation. Again there may be performance implications to consider since the internal raycasting method has to be modified to support clipping planes. 

From the X3D standard point of view, I am not aware on the relationship between the VolumeData node and the clipping plane entity. I guess, a new definition (let's say, VolumeClipPlaneNodes) might be necessary in the X3D standard.

**Comment by jcongote** [comment]
Hello Ander,

There is not need to implement the clipping planes as part of the shaders,
you can implement the clipping planes as part of a the geometry of the cube
and assing the texture for the ray possition according to the point of view
of the ray. The MPR volume style node "http://examples.x3dom.org/volren/
volrenMPR_aorta.xhtml" works within this principe, the modification coluld
be made to position that plane as a clipping plane.

Regards,
John Congote

2015-08-21 5:52 GMT-05:00 Ander Arbelaiz <notifications@github.com>:

**Comment by aarbelaiz** [comment]
I have hacked a fix which allows to inspect the volume from inside. As expected, a conditional branch is required in the volume rendering GLSL shader, reducing slightly the performance.  

As the patch should be optional somehow, I propose to add an attribute to the _X3DVolumeData_ node `allowViewpointInside=true`. VolumeData could be another place, but this is totally open to discussion (the name too, of course). 

The default behaviour of this flag would be __true__. Therefore the volumes could be inspected from the inside by default. If this feature is not required, it could be deactivated to gain some performance.

Would this proposed attribute be accepted?

**Comment by mlimper** [comment]
> Would this proposed attribute be accepted?

Sounds okay to me. Yes.

**Comment by onehalfmv2** [comment]
Hello aarbelaiz.  Thanks for hacking a fix to see the volume from the inside!  How can I see this hack???!!

**Comment by aarbelaiz** [comment]
I will make a pull request when it is ready. You will be notified

**Comment by mlimper** [comment]
Thanks, should be in next dev build (latest  tomorrow), ready for testing.

**Comment by onehalfmv2** [comment]
It works! It works! It works!

Thank you!!!!!!!

**Comment by mlimper** [comment]
nice :-)

Thanks to everybody for pushing this. Please post here if you have a cool demo that we could feature in our blog to showcase this new feature.

**Comment by andreasplesch** [comment]
Is allowViewpointInside only applicable to IsoSurfaceVolumeData ? I would like to use it with RadarVolumeStyle.

**Comment by aarbelaiz** [comment]
`allowViewpointInside` should be available for all the X3DVolumeData nodes, thus inherited in the VolumeData, SegmentedVolumeData and IsoSurfaceVolumeData. The RadarVolumeStyle is an addition out of the X3D spec that differs from the base algorithms to consider the depth and it is not totally integrated yet within the other nodes. 

I will check if the same fix could be applied, whenever I have some time for this...

**Comment by andreasplesch** [comment]
Thanks. I would be great since RadarVolumeStyle has some nice and
convenient features such as intensityLimits (could be probably done with
TextureTransform on the transferFunction) and xsection.



On Mon, Jan 18, 2016 at 7:08 PM, Ander Arbelaiz <notifications@github.com>
wrote:

> allowViewpointInside should be available for all the X3DVolumeData nodes,
> thus inherited in the VolumeData, SegmentedVolumeData and
> IsoSurfaceVolumeData. The RadarVolumeStyle is an addition out of the X3D
> spec that differs from the base algorithms to consider the depth and it is
> not totally integrated yet within the other nodes.
>
> I will check if the same fix could be applied, whenever I have some time
> for this...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x3dom/x3dom/issues/537#issuecomment-172689374>.
>



-- 
Andreas Plesch
39 Barbara Rd.
Waltham, MA 02453
