### ISSUE TITLE
When zoomed away from 3d object a bit you get a black wall in 4 directions

### ISSUE THREAD

**Issue by shivajiwagh** [x3dom/x3dom#590]
When zoomed away from a 3d model bit you get a black wall in 4 directions. Is there a setting to control this? If yes is it available in api's? Or it is model specific?
Please have a look at the pictures
BEFORE:
![before](https://cloud.githubusercontent.com/assets/16300506/11803349/1c20b0ea-a320-11e5-9cfc-630d443ba711.PNG)

AND AFTER ZOOMING A BIT.
![after](https://cloud.githubusercontent.com/assets/16300506/11803359/322c3558-a320-11e5-9c2f-9f9be0445efd.PNG)

**Comment by tsturm** [comment]
Hi, can you provide an example file for testing?

**Comment by shivajiwagh** [comment]
Please find the model below.

[ficus.txt](https://github.com/x3dom/x3dom/files/62702/ficus.txt)

**Comment by tsturm** [comment]
Hi,

your model includes a [LOD-Node](http://www.web3d.org/documents/specifications/19775-1/V3.0/Part01/components/navigation.html#LOD) which specifies various levels of detail for the plant. If the distance between the viewpoint and the plant reach one of the specified ranges the level of detail changes. This works fine for the highest level because it contains the complete mesh. All lower levels uses only textures for a simplified visualization.

Are you sure the texture urls in the file are correct?

**Comment by shivajiwagh** [comment]
Thanks this helped a lot.

**Comment by tsturm** [comment]
@shivajiwagh: Can we close the issue?
