### ISSUE TITLE
IndexedLineSet appears colorless when inline in HTML, colored when in an X3D file

### ISSUE THREAD

**Issue by sevaa** [x3dom/x3dom#600]
Navigate to http://valekseyev.3dprintdev.niaid.nih.gov/x3d/#IndLine
Check the "Axes" box in the left nav bar
See how one lineset is colored while the other is not. The colored one comes from an X3D file loaded via &lt;inline url="..."&gt; while the colorless one comes straight from the HTML. These two shapesare identical. It goes like this:

&lt;Shape>
    &lt;IndexedLineSet coordIndex='0 1 -1 0 2 -1 0 3' colorIndex='0 0 -1 1 1 -1 2 2'&gt;
            &lt;Coordinate point='0.1 0.1 0.1 10 0.1 0.1 0.1 10 0.1 0.1 0.1 10'/&gt;
            &lt;Color color='1 0 0 0 1 0 0 0 1'/&gt;
    &lt;/IndexedLineSet&gt;
&lt;/Shape&gt;

**Comment by YuanxiangFranck** [comment]
I found the problem, self closing element is not valid in HTML5.
Because you did not close  Coordinate, the Color element was set as an element of Coordinate instead of being an element of IndexedLineSet. So x3dom did not parsed the colors.
If you tries to switch the two lines (Coordinate and color), there would be an error because the position cannot be found.

```html
        <IndexedLineSet  coordIndex='0 1 -1 0 2 -1 0 3 -1'
                        colorIndex='0 0 -1 1 1 -1 2 2 -1'>
          <Coordinate point='0 0 0, 10 0 0, 0 10 0, -0.10 0 10'></Coordinate>
          <Color  color='1 0 0, 0 1 0, 0 0 1,'></Color>
        </IndexedLineSet>
```

**Comment by sevaa** [comment]
Confirmed. Interesting piece of malfunction. Closing.
