### ISSUE TITLE
Shading is off on ccw=false IndexedTriangleSets

### ISSUE THREAD

**Issue by sevaa** [x3dom/x3dom#659]
Similar to #655

Look at the scene at http://www.jishop.com/temp/x3d/#CWIndTri

The two pyramids are supposed to look identical; they have the same material, same vertices and faces, the only difference is that the bottom one has ccw=false.

[CWIndTri.x3d.txt](https://github.com/x3dom/x3dom/files/433325/CWIndTri.x3d.txt)

**Comment by andreasplesch** [comment]
Here is a jsbin:

http://jsbin.com/xalenuhubo/1/edit?html,js,output

The fix is very similar to #655, eg. just passing on ccw. See //for sevaa lines.

At least, this seem to fix the default normalPerVertex='true' case.
You could also try the normalPerVertex='false' cases.

**Comment by andreasplesch** [comment]
ok, I tried normalPerVertex='false'

http://jsbin.com/pibimadiyo/1/edit?html,js,output

with ccw passed on to calcNormals(). Not black anymore, but now 'inside out' shading for ccw='false'

**Comment by andreasplesch** [comment]
For normalPerVertex='false' and ccw='false', rearranging the mesh positions (and indindices) array to have ccw ordering by swapping produces correct "outside out" shading:
http://jsbin.com/nubosetota/1/edit?html,js,output
But I do not know exactly why.
The ccw for calcNormals() is still needed which is confusing since now the mesh arrays should be equivalent to the ccw=true case.
So this would require further testing with a conformance suite.

**Comment by andreasplesch** [comment]
The first fix in
http://jsbin.com/xalenuhubo/1/edit?html,js,output
for the default normalPerVertex case should be correct and ready for a PR. Please feel free to submit one.

**Comment by sevaa** [comment]
Submitted, #660

**Comment by tsturm** [comment]
#660 is already merged so I close the issue
