### ISSUE TITLE
Documentation for SFMatrix4f.rotation<X|Y|Z> incorrect

### ISSUE THREAD

**Issue by DrX3D** [x3dom/x3dom#720]
The documentation in the class SFMatrix4f for the methods rotationX, rotationY, and rotationZ is incorrect. All three methods indicate that the argument (a) is an SFVec3f instead of SFFloat. It appears that the param statement is incorrect in the file src/fields.js. It should be:

 * @param {x3dom.fields.SFFloat} a - angle in radians

The argument 'a' is passed to Math.sin and Math.cos.

**Comment by andreasplesch** [comment]
Since in x3dom there is no x3dom.fields.SFFloat object (instead SFFloat field values [are used directly](https://github.com/x3dom/x3dom/blob/master/src/nodes/Core/X3DNode.js#L543) as Number objects) it may better to document as

@param {Number} a - angle in radians

This is still not quite correct since the parameter can be any object which can be converted to a Number:
http://www.ecma-international.org/ecma-262/6.0/#sec-function-properties-of-the-math-object

In any case SFVec3f is obviously completely wrong.
