### ISSUE TITLE
NavigationInfo panning apears to be faulty on 1.7.2+

### ISSUE THREAD

**Issue by Nonnisi** [x3dom/x3dom#736]
Iv just spent a number of hours attempting to get a realistic walking interaction with NavigationInfo. I found that no matter what, the view would go crazy whenever the mouse was moved. However I assumed it was an issue with my implementation.

"<NavigationInfo type='WALK' speed='3'></NavigationInfo>"

I came upon this example which shows properly functioning walking, https://examples.x3dom.org/example/x3dom_walkThrough.html

However copying the exact x3d to my html page still resulted in the same crazy view jumping.

The example is on 1.7.1dev so I downgraded my page to that and everything works perfectly. I have tested on both release of 1.7.2 and dev version of 1.7.3 and the view is broken with both.

**Comment by andreasplesch** [comment]
The very similar (official) walking example here:

https://doc.x3dom.org/tutorials/animationInteraction/navigation/example.html

seems also broken. It is on 1.7.2.

It may be helpful to test 1.7.1 as well since it was released a couple months later than the 1.7.1dev in the example.

You could then just use 1.7.1 ?

**Comment by Nonnisi** [comment]
Tested, 1.7.1 stable has no issues. I cant find any dev versions of 1.7.2 to test, but it seems like the issue would have been introduced then.

**Comment by andreasplesch** [comment]
I looked through the commits in 2016:

The most likely candidate may be this refactoring:
https://github.com/x3dom/x3dom/commit/212fcc6b912d25ffaa060021fcbcc0ed76cce478

in preparation for turntable mode navigation.

https://github.com/x3dom/x3dom/tree/68976e08962c2107c094d3d8c3d71b712e7f39cf

is the commit just before this change.

You can download the repo from this date here: https://github.com/x3dom/x3dom/archive/68976e08962c2107c094d3d8c3d71b712e7f39cf.zip

and build x3dom.js locally. Use manage.py to build. It needs python2.
```python2 manage.py --build debug```

In fact, I just tried building this version and it seemed to work fine. I put the dist here:

https://github.com/andreasplesch/x3dom/tree/gh-pages/x3dom-1.7.2May2016/x3dom-68976e08962c2107c094d3d8c3d71b712e7f39cf/dist/

You should be able to use:

https://rawgit.com/andreasplesch/x3dom/gh-pages/x3dom-1.7.2May2016/x3dom-68976e08962c2107c094d3d8c3d71b712e7f39cf/dist/x3dom-full.debug.js

If walk mode still works then, you could try a later version until you find the commit where it breaks.

**Comment by andreasplesch** [comment]
I made the May2016 17.2dev version a user script:

https://github.com/andreasplesch/x3dom/raw/gh-pages/x3dom-1.7.2May2016/x3dom-68976e08962c2107c094d3d8c3d71b712e7f39cf/dist/x3dom-full.user.js

This means you can use tampermonkey (or greasemonkey) to replace x3dom in an existing page with this version. Install tampermonkey, click on the use.js link above, which automatically installs as a user script after a confirmation, then reload page with tampermonkey enabled.

https://doc.x3dom.org/tutorials/animationInteraction/navigation/example.html then works with this 1.7.2dev version. This means walk mode broke later.

**Comment by andreasplesch** [comment]
Here are two more builds, at commits 
https://github.com/x3dom/x3dom/commit/212fcc6b912d25ffaa060021fcbcc0ed76cce478
https://github.com/andreasplesch/x3dom/tree/gh-pages/x3dom-1.7.2May2016/x3dom-212fcc6b912d25ffaa060021fcbcc0ed76cce478/dist
https://github.com/andreasplesch/x3dom/raw/gh-pages/x3dom-1.7.2May2016/x3dom-212fcc6b912d25ffaa060021fcbcc0ed76cce478/dist/x3dom-full.user.js

and
https://github.com/x3dom/x3dom/commit/564b0b8addcdb52fa233b2158e3ce9dd77cbf1c6
https://github.com/andreasplesch/x3dom/tree/gh-pages/x3dom-1.7.2May2016/x3dom-564b0b8addcdb52fa233b2158e3ce9dd77cbf1c6/dist
https://github.com/andreasplesch/x3dom/raw/gh-pages/x3dom-1.7.2May2016/x3dom-564b0b8addcdb52fa233b2158e3ce9dd77cbf1c6/dist/x3dom-full.user.js

The build after commit 212fcc6b912d25ffaa060021fcbcc0ed76cce478 right after the navigation refactoring gives me an error:
```
Uncaught TypeError: this._typeMapping[navType] is not a constructor
    at x3dom.registerNodeType.defineClass.fieldChanged.fieldName._heliUpdated.setType (eval at <anonymous> (:2:297), <anonymous>:3926:233)
    at new x3dom.registerNodeType.defineClass.fieldChanged.fieldName._heliUpdated (eval at <anonymous> (:2:297), <anonymous>:3925:1710)
    at x3dom.NodeNameSpace.setupTree (eval at <anonymous> (:2:297), <anonymous>:2805:57)
    at eval (eval at <anonymous> (:2:297), <anonymous>:2809:122)
    at NodeList.forEach (native)
    at <anonymous>:2:297
    at Function.value (eval at exec_fn (:1:108), <anonymous>:63:315)
    at x3dom.NodeNameSpace.setupTree (eval at <anonymous> (:2:297), <anonymous>:2809:61)
    at x3dom.X3DDocument._setup (eval at <anonymous> (:2:297), <anonymous>:1244:158)
    at next_step (eval at <anonymous> (:2:297), <anonymous>:1209:1001)
```
This is then fixed with the next build after commit 564b0b8addcdb52fa233b2158e3ce9dd77cbf1c6 but with this build then walk mode does not work properly in the example.

So it likely that commit 212fcc6b912d25ffaa060021fcbcc0ed76cce478 broke something in walk mode. Unfortunately, it is a large commit with the refactoring, so it could take quite a bit of investigation.

**Comment by andreasplesch** [comment]
I think I found the problem.
Before the refactoring, the .onDrag method in viewpoint here:
https://github.com/x3dom/x3dom/blob/68976e08962c2107c094d3d8c3d71b712e7f39cf/src/Viewarea.js#L1752
explicitly treated each navigation mode individually. For "walk" the view was not modified. Only ._dx/y and ._lastX/Y were updated.
After the refactoring, for some reason, now the equivalent .onDrag here
https://github.com/x3dom/x3dom/blob/master/src/nodes/Navigation/modes/DefaultNavigation.js#L596
does not check anymore. It is invoked for walk mode and modifies the view matrices when the left button is pressed although it should not since this is done in navigateto.

Not sure what the proper fix is but going back to skipping the view matrix modification in .onDrag for walk mode (and probably game mode) seems to fix walk mode.

**Comment by andreasplesch** [comment]
Ok, here is a user (tampermonkey) script which fixes walk mode:
https://gist.github.com/andreasplesch/fc0e3485daa20fb3f0438047e6ec53bc/raw/cdd096d3f3506f28ffff74fb7ed6c1849f7d5206/x3dom_walk_mode_fixer.user.js
It modifies the .onDrag method in DefaultNavigation.js as outlined.
I do not really think this is the proper solution but it seems to work. Could provide a PR but @skluge should take a look.

**Comment by andreasplesch** [comment]
It looks like a more proper solution would be to start to use the new navigation infrastructure and have a WalkNavigation.js implementation. It would be largely identical to DefaultNavigation.js, eg based on it similar to TurntableNavigation.js, but redefine the onDrag method. Later,  it would be easier to perhaps enhance it for touch events and such. This means a bit more code but a cleaner structure.

**Comment by andreasplesch** [comment]
https://gist.github.com/andreasplesch/c0a709d60039cb712d25f1bc6d13a2e6#file-x3dom_walkmode-user-js

has what I have in mind. There is a new x3dom.WalkNavigation which is registered as in NavigationInfo.js as a separate navigation implementation. @skluge woud this be preferrable ?

**Comment by andreasplesch** [comment]
I submitted #737 which addresses this issue.

**Comment by Nonnisi** [comment]
Thanks for all your help Andreas. I would like to clarify though that while walking was the specific use case for me, NavigationInfo panning is faulty on all types. Walk, Fly, LookAt etc. 

Your fix appears to be limited to walking, however a fix should be developed for all types.

**Comment by andreasplesch** [comment]
Ah, ok, that sounds like all the original if (navTypes == ..) checks in onDrag() in https://github.com/x3dom/x3dom/blob/68976e08962c2107c094d3d8c3d71b712e7f39cf/src/Viewarea.js#L1752
need to go back in.
Examine and turntable presumably still work ?
helicopter ?

**Comment by andreasplesch** [comment]
Probably best to submit separate issues with a use case.

**Comment by Nonnisi** [comment]
Examine and Turntable do appear to work fine on 173, Helicopter does not.

**Comment by andreasplesch** [comment]
Thanks. Well, proper navigation helps everybody.
I made a small fix here:
https://github.com/andreasplesch/x3dom/blob/navigation-onDrag/src/nodes/Navigation/modes/DefaultNavigation.js#L619
Try it here:
https://rawgit.com/andreasplesch/x3dom/navigation-onDrag/test/functional/walkThrough.html
You can use the fixed DefaultNavigation by including the script from here:
https://rawgit.com/andreasplesch/x3dom/navigation-onDrag/src/nodes/Navigation/modes/DefaultNavigation.js

**Comment by Nonnisi** [comment]
Thanks for the fix!
Your walkThrough.html test page is causing Firefox to crash for me, however I included the DefaultNavigation script in my test site and all navigation appears to be working on 173dev.

The movement even seems a little smoother than it did on 171.

**Comment by andreasplesch** [comment]
Wow, FF crashes. Walk mode should be even smoother if you additionally include this js with dampening of to ground adjustments:
https://rawgit.com/andreasplesch/x3dom/smooth-walk/src/nodes/Navigation/modes/WalkNavigation.js
After tomorrow when the next nightly build becomes available.

**Comment by andreasplesch** [comment]
Submitted #738 to address the other modes.

**Comment by Nonnisi** [comment]
I didn't go into great testing, but the WalkNavigation.js when included after all others causes all navigation to be forced to walk mode with no ability to change.

**Comment by andreasplesch** [comment]
You will need the next nightly build which has PR #737 incorporated.

**Comment by andreasplesch** [comment]
@Nonnisi : Can this issue closed ? You could close yourself.

**Comment by Nonnisi** [comment]
Confirmed to have been fixed in the most recent dev build. Thanks for your help Andreas.
