### ISSUE TITLE
support Lines in glTFloader

### ISSUE THREAD

**Issue by doczoidberg** [x3dom/x3dom#754]
please support Lines in the glTFloader. 

I looked at the source coude and think that deeper knowledge of x3dom is necessary to implement it?

**Comment by doczoidberg** [comment]
or is there a way to render a mesh (data from glb file) as a wireframe?

where can I adjust the source? please give me a hint

**Comment by andreasplesch** [comment]
Here is all the gltf handling:

https://github.com/x3dom/x3dom/blob/master/src/util/glTF/

The final render function called from gfx_webgl.js  is here:

https://github.com/x3dom/x3dom/blob/master/src/util/glTF/glTFContainer.js#L96

Here is the TODO for points and lines:

https://github.com/x3dom/x3dom/blob/master/src/util/glTF/glTFLoader.js#L165

See whereever else faces or numfaces or similar are expected since lines would not have faces.

https://github.com/x3dom/x3dom/blob/master/src/nodes/Rendering/IndexedLineSet.js

shows how the x3dom ._mesh object needs to be constructed. gltfLoader probably already does most of this. _mesh.primType is "LINES". This is translated by
https://github.com/x3dom/x3dom/blob/master/src/util/Utils.js#L913
to gl.LINES in gfx_webgl.js. So using gl.LINES above should be possible.

gfx_webgl.js may not need adjustments but is important to walk through as well. It is large but manageable. (Ignore picking, background, foreground ..).

In the end not too much code may be needed but it will take time.

**Comment by andreasplesch** [comment]
for wireframe see https://github.com/x3dom/x3dom/issues/756#issuecomment-319069517

**Comment by doczoidberg** [comment]
thanks for your long answer. I will look into it although I have many question marks in my head for now.

**Comment by andreasplesch** [comment]
It will take a while to work through the existing render path.

Thinking about it, a simpler solution may be to make polyMode here
https://github.com/x3dom/x3dom/blob/master/src/util/glTF/glTFContainer.js#L96
a per shape parameter, perhaps attached to this.material. Currently polyMode is a global parameter from viewarea._points .

**Comment by andreasplesch** [comment]
I looked at the gltf loader code more and went through some experiments, so I think I understand it better now. It still looks like not too much is needed. If you have a (simple) gltf v.1.0 example binary gltf with LINES primitives (primitive mode: GL_LINES (1)), I could give it a spin.

Most gltf viewers and loaders probably currently only support triangles, and I could not find any gltf 1.0 examples for LINES, even in the official gltf example models:
https://github.com/KhronosGroup/glTF-Sample-Models/issues/106

**Comment by doczoidberg** [comment]
I created a simple python glb generator for testing purposes of glb in x3dom:

https://github.com/doczoidberg/glbgenerator

any ideas why x3dom throws the error?
```
RangeError: Invalid typed array length: 1684370261
 /polyfills.bundle.js:2740
```

**Comment by andreasplesch** [comment]
You would need to step through with the debugger. `"uri":"data:,"` looks suspect.
You may consider generating a regular text encoded glTF v.1.0, and then converting it with `gltf-pipeline` .

**Comment by doczoidberg** [comment]
works with the gltf 2.0 loader now. example file: https://raw.githubusercontent.com/mrdoob/three.js/dev/examples/models/gltf/OutlinedBox/OutlinedBox.gltf
