### ISSUE TITLE
Audio is not playing in browser when x3d file is converted in html

### ISSUE THREAD

**Issue by shona14** [x3dom/x3dom#773]
In this file audio is playing with BSContact player or any other player but when i convert it to html it does not work in firefox or chrome browsers. I am also attaching a file converted in 
[blade.zip](https://github.com/x3dom/x3dom/files/1347258/blade.zip)
html& x3d file.

**Comment by andreasplesch** [comment]
It turns out that x3dom has an additional 'enabled' field for AudioClip which needs to be set to 'true': 

https://x3dom-copter.glitch.me/

The default value for 'enabled' is 'false':

https://github.com/x3dom/x3dom/blob/master/src/nodes/Sound/AudioClip.js#L48

contrary to the documentation:

https://doc.x3dom.org/author/Sound/AudioClip.html


https://github.com/x3dom/x3dom/commit/161a2fea63688d1b0b6eea878dcf78376f1e65e4

https://github.com/x3dom/x3dom/issues/351 has a discussion.

is the commit when the default was changed to 'false' for some reason.

**Comment by andreasplesch** [comment]
Unrelated, the scene is using touchtime to control animations. See #771 for tracking and a potential solution.

**Comment by andreasplesch** [comment]
You are welcome.
