### ISSUE TITLE
Object's texture in scene not delete after removing Appearance node

### ISSUE THREAD

**Issue by stefaniapedrazzi** [x3dom/x3dom#820]
After removing an Appearance field with texture child, the appearance of the objects in the scene doesn't change and the texture is not removed even if the ImageTexture node is correctly removed from HTML document.

Here is a jsfiddle showing the issue: when clicking on the button the Appearance node is removed but the scene is not updated
https://jsfiddle.net/spedrazzi/7b4rq7n2/12/

But it works removing directly the ImageTexture node.

**Comment by andreasplesch** [comment]
https://jsfiddle.net/7b4rq7n2/20/

shows that the issue is limited to materials with textures.

**Comment by andreasplesch** [comment]
Here is what happens when a node is removed:

https://github.com/x3dom/x3dom/blob/07cc3b365a32d66bac6d153c23fcfba66be2140d/src/nodes/Core/X3DNode.js#L100

Although all children get removed recursively including the texture node, the problem is that when the texture node gets removed, its parent (the Appearance node) is already removed (unlinked) from the shape node and shape._dirty.texture = true; here

https://github.com/x3dom/x3dom/blob/stable/1.7.x/src/nodes/Texturing/X3DTextureNode.js#L155

is not reached.

Since the workaround is not too bad, let's give this some more thought.

**Comment by andreasplesch** [comment]
One idea is to take advantage of the fact that parent.nodeChanged() is called after the node is removed:

https://github.com/x3dom/x3dom/blob/17914ce84ee25b45525f62c5ae21157acacab527/src/X3DDocument.js#L224

and just dirty the texture or all in shape.nodeChanged:

https://jsfiddle.net/7b4rq7n2/34/

This works (!) and should be safe since nodeChanged otherwise is only (mostly?) called when a new node is inserted. Also it seems like a minimal tweak. Since Shape is so central there will be need to be thorough testing and critical assessing.

**Comment by andreasplesch** [comment]
http://x3dom-builds.surge.sh/build_0/
http://x3dom-builds.surge.sh/build_0/x3dom-full.debug.js
is a test build with the fix. Please give it a try.

**Comment by stefaniapedrazzi** [comment]
Thank you! I will try the test build today.

**Comment by stefaniapedrazzi** [comment]
I tested adding and removing nodes and everything seems to work fine with the test build and the issue removing the Appearance node is fixed.
