### ISSUE TITLE
zNear bug: shootRay() returns incorrect coordinates when zNear is comparable to crossing distance

### ISSUE THREAD

**Issue by okdzhimiev** [x3dom/x3dom#821]
Hi,
While implementing dragging of a sphere over a surface (using shootRay function) I have noticed that for 'close' objects the ray's pickPosition is incorrect which results in in placing center of the sphere farther along the ray than it should by zNear value.

FIX:
Couldn't find a place in the x3dom.js right away, so I made a fix in the outer code:
[x3dom_functions.js#L360](https://github.com/Elphel/x3domlet/blob/master/js/x3dom_functions.js#L360)

[Demo](https://community.elphel.com/3d+map/viewer.html?path=1488237915_992276&ver=x3d316&rating=5) - move cursor around with **ctrl** pressed.

Here's a cleaner version:
```
var Element = document.getElementById('x3d_id');

function shootRay_fixed(x,y){
  var ray =  Element.runtime.shootRay(x,y);
  ray.pickPosition = zNear_bug_correction(ray.pickPosition);
  return ray;
}

function zNear_bug_correction(vec){
  var mat = Element.runtime.viewMatrix();
  var zNear = Element.runtime.viewpoint().getNear();

  var vec_cam = mat.multFullMatrixPnt(vec);
  var z1 = vec_cam.z + zNear;
  var zratio = z1 / vec_cam.z;

  vec_cam.x = zratio*vec_cam.x;
  vec_cam.y = zratio*vec_cam.y;
  vec_cam.z = z1;

  vec_out = mat.inverse().multFullMatrixPnt(vec_cam);
  return vec_out;
}
```

**Comment by andreasplesch** [comment]
shootRay() and all the other Runtime functions are here:
https://github.com/x3dom/x3dom/blob/master/src/Runtime.js#L328
It uses x3dom's shader based picking which works by rendering a (color coded) distance map in a shader and then calculating the location by scaling the direction to the point. This is much faster than looking directly for intersections with triangles. At large distances/numbers there are problems due to limited numerical precision but I do not know what the problems at very small distances may be. Either the distance is off or the direction. It seems the distance may be. You may have an idea why adding zNear to camera space z works for correcting ?

For now, it may suffice to add the correction to runtime,shootRay() once there is testing that this does not break default use cases. You should be able to just redefine x3dom.Runtime.prototype.shootRay() and then use it.

**Comment by AndreyFilippov** [comment]
We did not dig much - why that could happen, but I'm pretty sure that the direction is correct and the distance is off (by zNear in z direction). And it is understandable why it remained unnoticed - usually Znear is much smaller than the distances of interest. It was not so in our case, and without the correction the centers of the spherical markers appeared below the horizontal surface (pavement). It is easy to reproduce with a simple cube too - just make sure that Znear is large enough to notice.

**Comment by andreasplesch** [comment]
Thanks. Do you have a minimal example jsfiddle or similar to work on ? Could be based on
https://doc.x3dom.org/tutorials/animationInteraction/picking/example.html

**Comment by AndreyFilippov** [comment]
I tried to modify your example (frame went off, but it is still usable). I copied files to http://community.elphel.com/files/znear/
http://community.elphel.com/files/znear/original.html is supposed to be a copy of your example
http://community.elphel.com/files/znear/far_cylinder.html - is modified:
1) I moved a cylinder far away (z=5000). As far as I remember Znear is set to a certain fraction of the Z far, so this example has increased Znear.
2) I increased the radius of marker to 5 (from1) - just to make offset to be more visible.

You will see, that now the center of the marker sphere is farther away. An it is not the insufficient precision - applying that function that Oleg suggested would fix the problem nicely.

**Comment by andreasplesch** [comment]
Thanks. I start to suspect that the 'from' camera position is off. It is derived from the view matrix:

https://github.com/x3dom/x3dom/blob/0202c9ae9aa32ee850d540434c4f00d4d9523ac2/src/gfx_webgl.js#L2930

**Comment by andreasplesch** [comment]
Here is jsfiddle with explicit zNear/zFar

https://jsfiddle.net/andreasplesch/ok3b8ruo/16/

**Comment by andreasplesch** [comment]
Ok. Using the original viewmatrix derived 'from' seems to fix the issue:
https://x3dom-znear-picking-fix.glitch.me/
This does not use the correction but a fixed gfx_webgl.

Could you please try to load 
https://x3dom-znear-picking-fix.glitch.me/gfx_webgl.js
after x3dom.js
```
<script type='text/javascript' src='https://www.x3dom.org/download/x3dom.js'> </script>
<script type='text/javascript' src='https://x3dom-znear-picking-fix.glitch.me/gfx_webgl.js'> </script>
```
in your app and check if a correction is still necessary ?

**Comment by AndreyFilippov** [comment]
Andreas, thank you - Oleg will try tomorrow. But I'm pretty sure it will fix the issue as it did on the minimal demo.

**Comment by andreasplesch** [comment]
The normal calculation needed to be adjusted accordingly, by also using the original 'from'.
Example with large znear:
https://x3dom-znear-picking2.glitch.me/

**Comment by okdzhimiev** [comment]
Tested in our application - everything works fine now. Thanks. 
Is there a stable release soon or should we use master branch?

**Comment by andreasplesch** [comment]
Let me build a test release, test Touchsensor X3D examples, submit a PR and then probably merge into master. Touchsensor uses the same picking mechanism.

The dev version then will be available on x3dom.org. 

The more thorough testing is necessary since picking is a sensitive and critical piece although I do not anticipate problems.

Stable releases currently are rel. low priority. It does not take too much to fork and build from any commit. GitHub also allows downloading a zipped tree from any commit. it then just takes a quick python script invocation to build.

**Comment by andreasplesch** [comment]
There is now a test build at
https://x3dom-builds.surge.sh/build_9/x3dom.debug.js
https://x3dom-builds.surge.sh/build_9/
