### ISSUE TITLE
CommonSurfaceShader and emissiveTexture

### ISSUE THREAD

**Issue by gkovacsds** [x3dom/x3dom#840]
Should the "emissiveTexture" feature work?
Examining network traffic, the texture for emissiveTexture is not downloaded:

Example: 

```
				<CommonSurfaceShader ambientFactor="0.6 0.6 0.6" diffuseFactor="1 1 1" specularFactor="1 1 1" shininessFactor="0"  emissiveFactor="1 1 1">
					<ImageTexture containerField="diffuseTexture" url='black.png'></ImageTexture> 
					<ImageTexture containerField="emissiveTexture" url='board.png'></ImageTexture> 
				</CommonSurfaceShader>
```

**Comment by andreasplesch** [comment]
looking for a live example, there should be one. diffuseTexture works ?

**Comment by gkovacsds** [comment]
Yes, diffuseTexture works, specular too.
Here's one example with the above shader:

https://drive.google.com/open?id=1zmfUJMt_IB3T4r7wOUZXRLWzmOPEIWM3

Actually my goal was to display a red light somehow on a green object...

**Comment by andreasplesch** [comment]
I checked ShaderDynamic.js (the main shader generator). CSS EmissiveMap does not seem to be implemented.

Could you just use a regular green Material for a dedicated Shape for the green light ?

(I will probably put the example on GitHub or glitch once I had a chance to look at it. Rawgit.com would serve the HTML correctly.)

**Comment by gkovacsds** [comment]
Thanks for the feedback, I'll think of this layered solution, or maybe just skip this, not really important, but would have looked nice.

**Comment by andreasplesch** [comment]
For modern materials and binary loading, you could look into glTF. glTF1 is available with traditional Phong shading and emissive texture etc. . glTF2 with PBR shading is developed in the webvr branch.

**Comment by andreasplesch** [comment]
I modified your example a bit and put it here:

https://x3dom-emissivetexture-test.glitch.me/

This uses a modified shader as a proof of concept:

https://glitch.com/edit/#!/x3dom-emissivetexture-test?path=ShaderDynamic.js:298:13

It just uses the supplied specular map as the emissive map.

Since the diffuse texture is multiplied in, a black (0,0,0) diffuse texture will just swallow all colors. But the black diffuse factor works. Not sure why they are treated differently. One could use a diffuse texture with a white mask for the emissive pixels.

There would be a bit of plumbing necessary to get an emissive texture from the node but perhaps not too cumbersome.

**Comment by gkovacsds** [comment]
Thank you, it's working great!
As I see I can just remove the diffuseTexture, and keeping a little diffuseFactor /I chose 0.2, so it's keeping the texture colors good enough without going too white/.
Only drawback is that other objects placed on the scene are stronger lit, but I set up attenuation values which look OK for the purpose.

**Comment by andreasplesch** [comment]
Glad to see that it works for you. Just be aware that this is a rather ugly hack, and removes specular textures, although one can still use the specularFactor for uniform specular highlights.

**Comment by andreasplesch** [comment]
Closing. Please reopen as necessary.
